# Generated by Django 6.0 on 2025-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='laboratory_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
