# Generated by Django 6.0 on 2025-12-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
        ('billing', '0002_alter_bill_laboratory_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='laboratory_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='medicine_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
